# Generated by Django 3.1.6 on 2021-03-27 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carserviceapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='cost',
        ),
    ]
