# Generated by Django 3.1.6 on 2021-03-26 22:26

from django.db import migrations, models
import multiselectfield.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('carserviceapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('shop_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shop_name', models.CharField(max_length=50)),
                ('owner_name', models.CharField(max_length=50)),
                ('shop_email', models.EmailField(max_length=60, unique=True)),
                ('shop_contact', models.IntegerField(unique=True)),
                ('owner_contact', models.IntegerField(unique=True)),
                ('services', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Vehicle Servicing'), (2, 'Vehicle Breakdown Support'), (3, 'Vehicle Parts Replacement'), (4, 'Vehicle Modification'), (5, 'Body Repair & Repainting')], max_length=9)),
                ('shop_image', models.ImageField(upload_to='')),
                ('service_charge', models.IntegerField()),
            ],
        ),
    ]
