# Generated by Django 3.1.6 on 2021-03-27 06:10

import address.models
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20200830_1851'),
        ('carserviceapp', '0002_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='shop_location',
            field=address.models.AddressField(default=1, on_delete=django.db.models.deletion.CASCADE, to='address.address'),
            preserve_default=False,
        ),
    ]
