# Generated by Django 3.1.6 on 2021-03-27 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('carserviceapp', '0003_shop_shop_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('services_required', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Vehicle Servicing'), (2, 'Vehicle Breakdown Support'), (3, 'Vehicle Parts Replacement'), (4, 'Vehicle Modification'), (5, 'Body Repair & Repainting')], max_length=9)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('cost', models.IntegerField()),
                ('customer', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('hired_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carserviceapp.shop')),
            ],
        ),
    ]
