# Generated by Django 3.1.6 on 2021-03-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carserviceapp', '0004_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='service_charge',
            new_name='body_repair_and_repainting_charge',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='services',
        ),
        migrations.AddField(
            model_name='shop',
            name='vehicle_breakdown_Support_charge',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='vehicle_modification_charge',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='vehicle_parts_Replacement_charge',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='vehicle_servicing_charge',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
